apiVersion: v2
name: s3-mirror
description: A Kubernetes S3 proxy with real-time mirroring and database tracking
type: application
version: 1.0.3
appVersion: "1.0.3"
keywords:
  - s3
  - proxy
  - mirror
  - backup
  - aws
home: https://github.com/starburst997/k8s-s3-mirror
sources:
  - https://github.com/starburst997/k8s-s3-mirror
maintainers:
  - name: JD Boivin
    url: https://github.com/starburst997
