apiVersion: v1
kind: Secret
metadata:
  name: s3-proxy-secrets
  namespace: s3-mirror
type: Opaque
stringData:
  # Main S3 credentials - these are used by the proxy to access your primary S3
  MAIN_ACCESS_KEY: "your-main-s3-access-key"
  MAIN_SECRET_KEY: "your-main-s3-secret-key"

  # Mirror S3 credentials - these are used for the backup S3
  MIRROR_ACCESS_KEY: "your-mirror-access-key"
  MIRROR_SECRET_KEY: "your-mirror-secret-key"

  # PostgreSQL connection string
  POSTGRES_URL: "postgres://username:password@postgres-host:5432/s3_mirror"