apiVersion: v1
kind: Service
metadata:
  name: s3-proxy
  namespace: s3-mirror
  labels:
    app: s3-proxy
spec:
  type: ClusterIP
  # Fixed ClusterIP for hostAliases usage
  clusterIP: 10.96.100.100
  selector:
    app: s3-proxy
  ports:
  - name: https
    port: 443
    targetPort: 8443
    protocol: TCP
  sessionAffinity: None