# Simplified sidecar deployment without database tracking
# This only provides S3 mirroring without persistence
---
apiVersion: v1
kind: Namespace
metadata:
  name: myapp-simple
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: myapp-s3-config
  namespace: myapp-simple
data:
  MAIN_S3_ENDPOINT: "https://s3.amazonaws.com"
  MIRROR_S3_ENDPOINT: "https://s3.us-west-000.backblazeb2.com"
  MIRROR_BUCKET_PREFIX: "myapp-backup-"
---
apiVersion: v1
kind: Secret
metadata:
  name: myapp-s3-secrets
  namespace: myapp-simple
type: Opaque
stringData:
  MAIN_ACCESS_KEY: "your-main-access-key"
  MAIN_SECRET_KEY: "your-main-secret-key"
  MIRROR_ACCESS_KEY: "your-mirror-access-key"
  MIRROR_SECRET_KEY: "your-mirror-secret-key"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-simple
  namespace: myapp-simple
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp-simple
  template:
    metadata:
      labels:
        app: myapp-simple
    spec:
      containers:
        # Your application
        - name: app
          image: your-app:latest
          ports:
            - containerPort: 3000
          env:
            - name: S3_ENDPOINT
              value: "http://localhost:8080"
            - name: S3_FORCE_PATH_STYLE
              value: "true"
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"

        # S3 Proxy sidecar (without database)
        - name: s3-proxy
          image: ghcr.io/starburst997/k8s-s3-mirror:latest
          ports:
            - containerPort: 8080
          env:
            # S3 Configuration
            - name: MAIN_S3_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: myapp-s3-config
                  key: MAIN_S3_ENDPOINT
            - name: MAIN_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: myapp-s3-secrets
                  key: MAIN_ACCESS_KEY
            - name: MAIN_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: myapp-s3-secrets
                  key: MAIN_SECRET_KEY
            - name: MIRROR_S3_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: myapp-s3-config
                  key: MIRROR_S3_ENDPOINT
            - name: MIRROR_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: myapp-s3-secrets
                  key: MIRROR_ACCESS_KEY
            - name: MIRROR_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: myapp-s3-secrets
                  key: MIRROR_SECRET_KEY
            - name: MIRROR_BUCKET_PREFIX
              valueFrom:
                configMapKeyRef:
                  name: myapp-s3-config
                  key: MIRROR_BUCKET_PREFIX
            # Disable database tracking for simplicity
            - name: DISABLE_DATABASE
              value: "true"
            # Minimal logging
            - name: LOG_LEVEL
              value: "error"
          resources:
            requests:
              memory: "32Mi"
              cpu: "25m"
            limits:
              memory: "128Mi"
              cpu: "100m"