name: Release Helm Chart

on:
  push:
    branches:
      - main
    paths:
      - 'helm/**'
  release:
    types: [published]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Package Helm chart
        run: |
          helm package helm/s3-mirror -d /tmp

      - name: Create gh-pages branch if not exists
        run: |
          # Check if gh-pages exists on remote
          if git ls-remote --exit-code origin gh-pages; then
            git checkout gh-pages
            git pull origin gh-pages
          else
            # Create orphan branch (no parent history) for clean Helm repository
            git checkout --orphan gh-pages
            # Remove all files from working tree
            git rm -rf .
            git clean -fdx
          fi

      - name: Update Helm repository
        run: |
          mkdir -p charts

          # Move new chart package
          mv /tmp/s3-mirror-*.tgz charts/

          # Generate/update index.yaml (preserves existing charts)
          helm repo index charts --url https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/charts --merge charts/index.yaml || helm repo index charts --url https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/charts

          # Add all changes
          git add .

          # Commit only if there are changes
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update Helm chart repository"
            git push origin gh-pages
          fi