name: Release Helm Chart

on:
  push:
    branches:
      - main
    paths:
      - "helm/**"
  release:
    types: [published]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Package and Push Helm chart
        run: |
          # Package the Helm chart
          helm package helm/s3-mirror

          # Get the chart version from Chart.yaml
          CHART_VERSION=$(helm show chart helm/s3-mirror | grep '^version:' | awk '{print $2}')

          # Convert owner name to lowercase (OCI registry requires lowercase)
          OWNER_LOWER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')

          # Push to GitHub Container Registry using OCI
          helm push s3-mirror-${CHART_VERSION}.tgz oci://ghcr.io/${OWNER_LOWER}/charts

          echo "Chart pushed to: ghcr.io/${OWNER_LOWER}/s3-mirror:${CHART_VERSION}"
          echo ""
          echo "To use this chart:"
          echo "  helm install s3-mirror oci://ghcr.io/${OWNER_LOWER}/s3-mirror --version ${CHART_VERSION}"

      - name: Make package public
        run: |
          # Get package name (just the chart name part)
          PACKAGE_NAME="s3-mirror"

          # Make the package public using GitHub API
          curl -X PATCH \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/user/packages/container/${PACKAGE_NAME}/versions" \
            -d '{"visibility":"public"}' || true
